dist: xenial
matrix:
  include:
    - language: android
      dist: xenial
      jdk: oraclejdk8
      android:
        components:
          - platform-tools
          - tools
          - android-27
          - extras-android-m2repository
          - extras-google-m2repository
          
install:
  - echo y | sdkmanager "ndk;17.2.4988734"
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager --channel=3 --channel=1 "cmake;3.10.2.4988404"
    #  - echo y | sdkmanager "lldb;3.1"
    #  - sdkmanager --update
before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk
  
script:
  - chmod +x ./build_openalpr_android.sh
  - ./build_openalpr_android.sh
  
deploy:
  provider: releases
  api_key:
  secure: $tobeaddedlater
  file: "openalpr/android-build/*/*"
  skip_cleanup: true
  overwrite: true
  
  on:
    tags: false
    repo: fantasyado/openalpr-android
    branch: master
