matrix:
  include:
    - language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - tools
script:
  - yes | sdkmanager "platforms;android-28"
  - chmod +x ./build_openalpr_android.sh
  - ./build_openalpr_android.sh
deploy:
  provider: npm
  email: leejoo71@gmail.com
  api_key:
    secure: $tobeaddedlater
  on:
    tags: true
    repo: leejoo71/openalpr-android
    branch: master
