matrix:
  include:
    - language: android
      jdk: oraclejdk8
      android:
        components:
          - build-tools-28.0.3
          - platform-tools
          - android-28
          - tools
          - ndk
          - build-tools
          - cmake-3.10.2.4988404
          - lldb-3.1
          - extras-android-m2repository
          - extras-google-m2repository
          
script:
  - chmod +x ./build_openalpr_android.sh
  - ./build_openalpr_android.sh
  
deploy:
  provider: releases
  api_key:
    secure: $tobeaddedlater
  file: "path "
  skip_cleanup: true
  overwrite: true
  
  on:
    tags: true
    repo: leejoo71/openalpr-android
    branch: master
