matrix:
  include:
    - language: android
      jdk: oraclejdk8
      android:
        components:
          - build-tools-28.0.3
script:
  - yes | sdkmanager "tools" > /dev/null
  - yes | sdkmanager "platform-tools" > /dev/null
  - yes | sdkmanager "platforms;android-28" > /dev/null
  - yes | sdkmanager "ndk-bundle" > /dev/null
  - yes | sdkmanager "ndk;20.0.5594570" > /dev/null
  - yes | sdkmanager "build-tools;28.0.3" > /dev/null
  - yes | sdkmanager "cmake;3.10.2.4988404" > /dev/null
  - yes | sdkmanager "lldb;3.1" > /dev/null
  - yes | sdkmanager "extras;android;m2repository" > /dev/null
  - yes | sdkmanager "extras;google;m2repository" > /dev/null
  - chmod +x ./build_openalpr_android.sh
  - ./build_openalpr_android.sh
  
deploy:
  provider: releases
  api_key:
    secure: $tobeaddedlater
  file: "path "
  skip_cleanup: true
  overwrite: true
  
  on:
    tags: true
    repo: leejoo71/openalpr-android
    branch: master
